export const types = {
    // Sync
    FILL_POSTS:        'FILL_POSTS',
    CREATE_POST:       'CREATE_POST',
    REMOVE_POST:       'REMOVE_POST',
    CLEAR_POST:        'CLEAR_POST',
    LIKE_POST:         'LIKE_POST',
    UNLIKE_POST:       'UNLIKE_POST',
    // Async
    FETCH_POST_ASYNC:  'FETCH_POST_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
    REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
    LIKE_POST_ASYNC:   'LIKE_POST_ASYNC',
    UNLIKE_POST_ASYNC: 'UNLIKE_POST_ASYNC',

};
