export const types = {
    // Sync
    FILL_PROFILE:  'FILL_PROFILE',
    CLEAR_PROFILE: 'CLEAR_PROFILE',
    UPDATE_AVATAR: 'UPDATE_AVATAR',
    

    // Async
    UPDATE_NAME_ASYNC:   'UPDATE_NAME_ASYNC',
    UPDATE_AVATAR_ASYNC: 'UPDATE_AVATAR_ASYNC',
    UPDATE_PASSWORD_ASYNC: 'UPDATE_PASSWORD_ASYNC',

};
